import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

df = pd.read_csv('Ecommerce_Transactions_Data.csv')

print("Step 2: Date converted and Total Amount calculated...")
df['Date'] = pd.to_datetime(df['Date'])
df['Total_Amount'] = df['Quantity'] * df['Price']

completed_df = df[df['Quantity'] > 0].copy()
cancelled_df = df[df['Quantity'] < 0].copy()


print("Step 3: Making Question (a) Histogram plot...")
plt.figure(figsize=(10, 5))
sns.histplot(completed_df['Total_Amount'], bins=50, kde=True, color='skyblue')
plt.title('Distribution of Completed Transaction Amounts', fontsize=14, fontweight='bold')
plt.xlabel('Transaction Amount (£)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.tight_layout()
plt.savefig('distribution_of_transactions.png', dpi=300)
plt.close()


print("Step 4: Making Question (b) Time-Series Line chart...")
time_df = completed_df.set_index('Date').resample('ME')['Total_Amount'].sum().reset_index()

plt.figure(figsize=(12, 5))
plt.plot(time_df['Date'], time_df['Total_Amount'], marker='o', linewidth=2.5, color='#1f77b4')
plt.title('Monthly Total Transaction Amount Trend', fontsize=14, fontweight='bold')
plt.xlabel('Timeline (Months)', fontsize=12)
plt.ylabel('Total Revenue (£)', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('transaction_trend_over_time.png', dpi=300)
plt.close()


print("Step 5: Making Question (c) Bar chart...")
category_revenue = completed_df.groupby('Category')['Total_Amount'].sum().sort_values(ascending=False).reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(data=category_revenue, x='Total_Amount', y='Category', hue='Category',
            palette='viridis', legend=False)
plt.title('Total Revenue Generated by Product Category', fontsize=14, fontweight='bold')
plt.xlabel('Total Revenue (£)', fontsize=12)
plt.ylabel('Product Category', fontsize=12)
plt.tight_layout()
plt.savefig('revenue_by_category.png', dpi=300)
plt.close()


print("Step 6: Making Question (d) Customer Behaviour chart - Top Countries...")
country_revenue = completed_df.groupby('Country')['Total_Amount'].sum().sort_values(ascending=False).head(5).reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(data=country_revenue, x='Country', y='Total_Amount', hue='Country',
            palette='magma', legend=False)
plt.title('Top 5 Countries by Total Revenue Contribution', fontsize=14, fontweight='bold')
plt.xlabel('Country', fontsize=12)
plt.ylabel('Total Revenue (£)', fontsize=12)
plt.tight_layout()
plt.savefig('customer_behaviour_top_countries.png', dpi=300)
plt.close()


print("Step 7: Making Question (d) - Repeat vs One-Time Customers...")
customer_orders = completed_df.groupby('CustomerNo')['TransactionNo'].nunique().reset_index()
customer_orders.columns = ['CustomerNo', 'Order_Count']

repeat_vs_onetime = customer_orders['Order_Count'].apply(lambda x: 'Repeat Customer' if x > 1 else 'One-Time Customer')
repeat_summary = repeat_vs_onetime.value_counts().reset_index()
repeat_summary.columns = ['Customer_Type', 'Count']

plt.figure(figsize=(7, 7))
plt.pie(repeat_summary['Count'], labels=repeat_summary['Customer_Type'], autopct='%1.1f%%',
        colors=['#66b3ff', '#ff9999'], startangle=90, textprops={'fontsize': 12})
plt.title('Repeat vs One-Time Customers', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('repeat_vs_onetime_customers.png', dpi=300)
plt.close()


print("Step 8: Making Question (d) - Weekday Purchasing Pattern...")
completed_df['Weekday'] = completed_df['Date'].dt.day_name()
weekday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekday_revenue = completed_df.groupby('Weekday')['Total_Amount'].sum().reindex(weekday_order).reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(data=weekday_revenue, x='Weekday', y='Total_Amount', hue='Weekday',
            palette='crest', legend=False)
plt.title('Total Revenue by Day of the Week', fontsize=14, fontweight='bold')
plt.xlabel('Day of Week', fontsize=12)
plt.ylabel('Total Revenue (£)', fontsize=12)
plt.tight_layout()
plt.savefig('weekday_purchasing_pattern.png', dpi=300)
plt.close()


print("Step 9: Making Question (d) - Cancellation Rate by Category...")
df['Order_Status'] = df['Quantity'].apply(lambda x: 'Cancelled' if x < 0 else 'Completed')
cancel_rate = df.groupby('Category')['Order_Status'].apply(
    lambda x: (x == 'Cancelled').sum() / len(x) * 100
).sort_values(ascending=False).reset_index()
cancel_rate.columns = ['Category', 'Cancellation_Rate']

plt.figure(figsize=(10, 5))
sns.barplot(data=cancel_rate, x='Cancellation_Rate', y='Category', hue='Category',
            palette='rocket', legend=False)
plt.title('Cancellation Rate (%) by Product Category', fontsize=14, fontweight='bold')
plt.xlabel('Cancellation Rate (%)', fontsize=12)
plt.ylabel('Product Category', fontsize=12)
plt.tight_layout()
plt.savefig('cancellation_rate_by_category.png', dpi=300)
plt.close()

print("All the plots are successfully generated and saved in folders as well !")